FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main cmd/server/main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates curl bash

WORKDIR /root/

COPY --from=builder /app/main .

COPY --from=builder /app/entrypoint.sh .
RUN chmod +x entrypoint.sh

EXPOSE 8888

ENTRYPOINT ["./entrypoint.sh"]
