// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	application "ev-warranty-go/internal/application"

	entities "ev-warranty-go/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	uuid "github.com/google/uuid"
)

// ClaimAttachmentService is an autogenerated mock type for the ClaimAttachmentService type
type ClaimAttachmentService struct {
	mock.Mock
}

// Create provides a mock function with given fields: tx, claimID, file
func (_m *ClaimAttachmentService) Create(tx application.Tx, claimID uuid.UUID, file multipart.File) (*entities.ClaimAttachment, error) {
	ret := _m.Called(tx, claimID, file)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.ClaimAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, multipart.File) (*entities.ClaimAttachment, error)); ok {
		return rf(tx, claimID, file)
	}
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, multipart.File) *entities.ClaimAttachment); ok {
		r0 = rf(tx, claimID, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ClaimAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(application.Tx, uuid.UUID, multipart.File) error); ok {
		r1 = rf(tx, claimID, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByClaimID provides a mock function with given fields: ctx, claimID
func (_m *ClaimAttachmentService) GetByClaimID(ctx context.Context, claimID uuid.UUID) ([]*entities.ClaimAttachment, error) {
	ret := _m.Called(ctx, claimID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClaimID")
	}

	var r0 []*entities.ClaimAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.ClaimAttachment, error)); ok {
		return rf(ctx, claimID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.ClaimAttachment); ok {
		r0 = rf(ctx, claimID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ClaimAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, claimID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ClaimAttachmentService) GetByID(ctx context.Context, id uuid.UUID) (*entities.ClaimAttachment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.ClaimAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.ClaimAttachment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.ClaimAttachment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ClaimAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDelete provides a mock function with given fields: tx, claimID, attachmentID
func (_m *ClaimAttachmentService) HardDelete(tx application.Tx, claimID uuid.UUID, attachmentID uuid.UUID) error {
	ret := _m.Called(tx, claimID, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for HardDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(tx, claimID, attachmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClaimAttachmentService creates a new instance of ClaimAttachmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimAttachmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimAttachmentService {
	mock := &ClaimAttachmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
