// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ClaimAttachmentHandler is an autogenerated mock type for the ClaimAttachmentHandler type
type ClaimAttachmentHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// GetByClaimID provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) GetByClaimID(c *gin.Context) {
	_m.Called(c)
}

// GetByID provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) GetByID(c *gin.Context) {
	_m.Called(c)
}

// NewClaimAttachmentHandler creates a new instance of ClaimAttachmentHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimAttachmentHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimAttachmentHandler {
	mock := &ClaimAttachmentHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
