// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	application "ev-warranty-go/internal/application"

	entities "ev-warranty-go/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ClaimItemRepository is an autogenerated mock type for the ClaimItemRepository type
type ClaimItemRepository struct {
	mock.Mock
}

// CountByClaimID provides a mock function with given fields: ctx, claimID
func (_m *ClaimItemRepository) CountByClaimID(ctx context.Context, claimID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, claimID)

	if len(ret) == 0 {
		panic("no return value specified for CountByClaimID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, claimID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, claimID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, claimID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: tx, item
func (_m *ClaimItemRepository) Create(tx application.Tx, item *entities.ClaimItem) error {
	ret := _m.Called(tx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, *entities.ClaimItem) error); ok {
		r0 = rf(tx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByClaimID provides a mock function with given fields: ctx, claimID
func (_m *ClaimItemRepository) FindByClaimID(ctx context.Context, claimID uuid.UUID) ([]*entities.ClaimItem, error) {
	ret := _m.Called(ctx, claimID)

	if len(ret) == 0 {
		panic("no return value specified for FindByClaimID")
	}

	var r0 []*entities.ClaimItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.ClaimItem, error)); ok {
		return rf(ctx, claimID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.ClaimItem); ok {
		r0 = rf(ctx, claimID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ClaimItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, claimID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ClaimItemRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.ClaimItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.ClaimItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.ClaimItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.ClaimItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ClaimItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: ctx, claimID, status
func (_m *ClaimItemRepository) FindByStatus(ctx context.Context, claimID uuid.UUID, status string) ([]*entities.ClaimItem, error) {
	ret := _m.Called(ctx, claimID, status)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []*entities.ClaimItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]*entities.ClaimItem, error)); ok {
		return rf(ctx, claimID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []*entities.ClaimItem); ok {
		r0 = rf(ctx, claimID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ClaimItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, claimID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDelete provides a mock function with given fields: tx, id
func (_m *ClaimItemRepository) HardDelete(tx application.Tx, id uuid.UUID) error {
	ret := _m.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for HardDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID) error); ok {
		r0 = rf(tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteByClaimID provides a mock function with given fields: tx, claimID
func (_m *ClaimItemRepository) SoftDeleteByClaimID(tx application.Tx, claimID uuid.UUID) error {
	ret := _m.Called(tx, claimID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByClaimID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID) error); ok {
		r0 = rf(tx, claimID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SumCostByClaimID provides a mock function with given fields: tx, claimID
func (_m *ClaimItemRepository) SumCostByClaimID(tx application.Tx, claimID uuid.UUID) (float64, error) {
	ret := _m.Called(tx, claimID)

	if len(ret) == 0 {
		panic("no return value specified for SumCostByClaimID")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID) (float64, error)); ok {
		return rf(tx, claimID)
	}
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID) float64); ok {
		r0 = rf(tx, claimID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(application.Tx, uuid.UUID) error); ok {
		r1 = rf(tx, claimID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: tx, item
func (_m *ClaimItemRepository) Update(tx application.Tx, item *entities.ClaimItem) error {
	ret := _m.Called(tx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, *entities.ClaimItem) error); ok {
		r0 = rf(tx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: tx, id, status
func (_m *ClaimItemRepository) UpdateStatus(tx application.Tx, id uuid.UUID, status string) error {
	ret := _m.Called(tx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, string) error); ok {
		r0 = rf(tx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClaimItemRepository creates a new instance of ClaimItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimItemRepository {
	mock := &ClaimItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
