// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ClaimItemHandler is an autogenerated mock type for the ClaimItemHandler type
type ClaimItemHandler struct {
	mock.Mock
}

// Approve provides a mock function with given fields: c
func (_m *ClaimItemHandler) Approve(c *gin.Context) {
	_m.Called(c)
}

// Create provides a mock function with given fields: c
func (_m *ClaimItemHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *ClaimItemHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// GetByClaimID provides a mock function with given fields: c
func (_m *ClaimItemHandler) GetByClaimID(c *gin.Context) {
	_m.Called(c)
}

// GetByID provides a mock function with given fields: c
func (_m *ClaimItemHandler) GetByID(c *gin.Context) {
	_m.Called(c)
}

// Reject provides a mock function with given fields: c
func (_m *ClaimItemHandler) Reject(c *gin.Context) {
	_m.Called(c)
}

// NewClaimItemHandler creates a new instance of ClaimItemHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimItemHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimItemHandler {
	mock := &ClaimItemHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
