// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ClaimHandler is an autogenerated mock type for the ClaimHandler type
type ClaimHandler struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: c
func (_m *ClaimHandler) Cancel(c *gin.Context) {
	_m.Called(c)
}

// Complete provides a mock function with given fields: c
func (_m *ClaimHandler) Complete(c *gin.Context) {
	_m.Called(c)
}

// Create provides a mock function with given fields: c
func (_m *ClaimHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *ClaimHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// GetAll provides a mock function with given fields: c
func (_m *ClaimHandler) GetAll(c *gin.Context) {
	_m.Called(c)
}

// GetByID provides a mock function with given fields: c
func (_m *ClaimHandler) GetByID(c *gin.Context) {
	_m.Called(c)
}

// History provides a mock function with given fields: c
func (_m *ClaimHandler) History(c *gin.Context) {
	_m.Called(c)
}

// RequestInfo provides a mock function with given fields: c
func (_m *ClaimHandler) RequestInfo(c *gin.Context) {
	_m.Called(c)
}

// Review provides a mock function with given fields: c
func (_m *ClaimHandler) Review(c *gin.Context) {
	_m.Called(c)
}

// Submit provides a mock function with given fields: c
func (_m *ClaimHandler) Submit(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *ClaimHandler) Update(c *gin.Context) {
	_m.Called(c)
}

// NewClaimHandler creates a new instance of ClaimHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimHandler {
	mock := &ClaimHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
