// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	application "ev-warranty-go/internal/application"

	entities "ev-warranty-go/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	services "ev-warranty-go/internal/application/services"

	uuid "github.com/google/uuid"
)

// ClaimItemService is an autogenerated mock type for the ClaimItemService type
type ClaimItemService struct {
	mock.Mock
}

// Approve provides a mock function with given fields: tx, claimID, itemID
func (_m *ClaimItemService) Approve(tx application.Tx, claimID uuid.UUID, itemID uuid.UUID) error {
	ret := _m.Called(tx, claimID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(tx, claimID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: tx, claimID, cmd
func (_m *ClaimItemService) Create(tx application.Tx, claimID uuid.UUID, cmd *services.CreateClaimItemCommand) (*entities.ClaimItem, error) {
	ret := _m.Called(tx, claimID, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.ClaimItem
	var r1 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, *services.CreateClaimItemCommand) (*entities.ClaimItem, error)); ok {
		return rf(tx, claimID, cmd)
	}
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, *services.CreateClaimItemCommand) *entities.ClaimItem); ok {
		r0 = rf(tx, claimID, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ClaimItem)
		}
	}

	if rf, ok := ret.Get(1).(func(application.Tx, uuid.UUID, *services.CreateClaimItemCommand) error); ok {
		r1 = rf(tx, claimID, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByClaimID provides a mock function with given fields: ctx, claimID
func (_m *ClaimItemService) GetByClaimID(ctx context.Context, claimID uuid.UUID) ([]*entities.ClaimItem, error) {
	ret := _m.Called(ctx, claimID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClaimID")
	}

	var r0 []*entities.ClaimItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.ClaimItem, error)); ok {
		return rf(ctx, claimID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.ClaimItem); ok {
		r0 = rf(ctx, claimID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ClaimItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, claimID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ClaimItemService) GetByID(ctx context.Context, id uuid.UUID) (*entities.ClaimItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.ClaimItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.ClaimItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.ClaimItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ClaimItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDelete provides a mock function with given fields: tx, claimID, itemID
func (_m *ClaimItemService) HardDelete(tx application.Tx, claimID uuid.UUID, itemID uuid.UUID) error {
	ret := _m.Called(tx, claimID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for HardDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(tx, claimID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reject provides a mock function with given fields: tx, claimID, itemID
func (_m *ClaimItemService) Reject(tx application.Tx, claimID uuid.UUID, itemID uuid.UUID) error {
	ret := _m.Called(tx, claimID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(tx, claimID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: tx, claimID, itemID, cmd
func (_m *ClaimItemService) Update(tx application.Tx, claimID uuid.UUID, itemID uuid.UUID, cmd *services.UpdateClaimItemCommand) error {
	ret := _m.Called(tx, claimID, itemID, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(application.Tx, uuid.UUID, uuid.UUID, *services.UpdateClaimItemCommand) error); ok {
		r0 = rf(tx, claimID, itemID, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClaimItemService creates a new instance of ClaimItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimItemService {
	mock := &ClaimItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
