// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	external "ev-warranty-go/internal/infrastructure/external"

	mock "github.com/stretchr/testify/mock"
)

// DotnetClient is an autogenerated mock type for the DotnetClient type
type DotnetClient struct {
	mock.Mock
}

type DotnetClient_Expecter struct {
	mock *mock.Mock
}

func (_m *DotnetClient) EXPECT() *DotnetClient_Expecter {
	return &DotnetClient_Expecter{mock: &_m.Mock}
}

// CreateWorkOrder provides a mock function with given fields: ctx, req
func (_m *DotnetClient) CreateWorkOrder(ctx context.Context, req *external.CreateWorkOrderRequest) (*external.WorkOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkOrder")
	}

	var r0 *external.WorkOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *external.CreateWorkOrderRequest) (*external.WorkOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *external.CreateWorkOrderRequest) *external.WorkOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*external.WorkOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *external.CreateWorkOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWorkOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkOrder'
type DotnetClient_CreateWorkOrder_Call struct {
	*mock.Call
}

// CreateWorkOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *external.CreateWorkOrderRequest
func (_e *DotnetClient_Expecter) CreateWorkOrder(ctx interface{}, req interface{}) *DotnetClient_CreateWorkOrder_Call {
	return &DotnetClient_CreateWorkOrder_Call{Call: _e.mock.On("CreateWorkOrder", ctx, req)}
}

func (_c *DotnetClient_CreateWorkOrder_Call) Run(run func(ctx context.Context, req *external.CreateWorkOrderRequest)) *DotnetClient_CreateWorkOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*external.CreateWorkOrderRequest))
	})
	return _c
}

func (_c *DotnetClient_CreateWorkOrder_Call) Return(_a0 *external.WorkOrderResponse, _a1 error) *DotnetClient_CreateWorkOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DotnetClient_CreateWorkOrder_Call) RunAndReturn(run func(context.Context, *external.CreateWorkOrderRequest) (*external.WorkOrderResponse, error)) *DotnetClient_CreateWorkOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewDotnetClient creates a new instance of DotnetClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDotnetClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *DotnetClient {
	mock := &DotnetClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
