// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// OfficeHandler is an autogenerated mock type for the OfficeHandler type
type OfficeHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *OfficeHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *OfficeHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// GetAll provides a mock function with given fields: c
func (_m *OfficeHandler) GetAll(c *gin.Context) {
	_m.Called(c)
}

// GetById provides a mock function with given fields: c
func (_m *OfficeHandler) GetById(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *OfficeHandler) Update(c *gin.Context) {
	_m.Called(c)
}

// NewOfficeHandler creates a new instance of OfficeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOfficeHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *OfficeHandler {
	mock := &OfficeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
