// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "ev-warranty-go/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PartPort is an autogenerated mock type for the PartPort type
type PartPort struct {
	mock.Mock
}

type PartPort_Expecter struct {
	mock *mock.Mock
}

func (_m *PartPort) EXPECT() *PartPort_Expecter {
	return &PartPort_Expecter{mock: &_m.Mock}
}

// ReserveByOfficeIDAndCategoryID provides a mock function with given fields: office, categoryID
func (_m *PartPort) ReserveByOfficeIDAndCategoryID(office uuid.UUID, categoryID uuid.UUID) (*entity.Part, error) {
	ret := _m.Called(office, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for ReserveByOfficeIDAndCategoryID")
	}

	var r0 *entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*entity.Part, error)); ok {
		return rf(office, categoryID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *entity.Part); ok {
		r0 = rf(office, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(office, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartPort_ReserveByOfficeIDAndCategoryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveByOfficeIDAndCategoryID'
type PartPort_ReserveByOfficeIDAndCategoryID_Call struct {
	*mock.Call
}

// ReserveByOfficeIDAndCategoryID is a helper method to define mock.On call
//   - office uuid.UUID
//   - categoryID uuid.UUID
func (_e *PartPort_Expecter) ReserveByOfficeIDAndCategoryID(office interface{}, categoryID interface{}) *PartPort_ReserveByOfficeIDAndCategoryID_Call {
	return &PartPort_ReserveByOfficeIDAndCategoryID_Call{Call: _e.mock.On("ReserveByOfficeIDAndCategoryID", office, categoryID)}
}

func (_c *PartPort_ReserveByOfficeIDAndCategoryID_Call) Run(run func(office uuid.UUID, categoryID uuid.UUID)) *PartPort_ReserveByOfficeIDAndCategoryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartPort_ReserveByOfficeIDAndCategoryID_Call) Return(_a0 *entity.Part, _a1 error) *PartPort_ReserveByOfficeIDAndCategoryID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartPort_ReserveByOfficeIDAndCategoryID_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (*entity.Part, error)) *PartPort_ReserveByOfficeIDAndCategoryID_Call {
	_c.Call.Return(run)
	return _c
}

// UnReserveByID provides a mock function with given fields: id
func (_m *PartPort) UnReserveByID(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for UnReserveByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartPort_UnReserveByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnReserveByID'
type PartPort_UnReserveByID_Call struct {
	*mock.Call
}

// UnReserveByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *PartPort_Expecter) UnReserveByID(id interface{}) *PartPort_UnReserveByID_Call {
	return &PartPort_UnReserveByID_Call{Call: _e.mock.On("UnReserveByID", id)}
}

func (_c *PartPort_UnReserveByID_Call) Run(run func(id uuid.UUID)) *PartPort_UnReserveByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *PartPort_UnReserveByID_Call) Return(_a0 error) *PartPort_UnReserveByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartPort_UnReserveByID_Call) RunAndReturn(run func(uuid.UUID) error) *PartPort_UnReserveByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartPort creates a new instance of PartPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartPort {
	mock := &PartPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
