// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// UserHandler is an autogenerated mock type for the UserHandler type
type UserHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *UserHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *UserHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// GetAll provides a mock function with given fields: c
func (_m *UserHandler) GetAll(c *gin.Context) {
	_m.Called(c)
}

// GetByID provides a mock function with given fields: c
func (_m *UserHandler) GetByID(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *UserHandler) Update(c *gin.Context) {
	_m.Called(c)
}

// NewUserHandler creates a new instance of UserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserHandler {
	mock := &UserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
