// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ClaimAttachmentHandler is an autogenerated mock type for the ClaimAttachmentHandler type
type ClaimAttachmentHandler struct {
	mock.Mock
}

type ClaimAttachmentHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimAttachmentHandler) EXPECT() *ClaimAttachmentHandler_Expecter {
	return &ClaimAttachmentHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// ClaimAttachmentHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClaimAttachmentHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c *gin.Context
func (_e *ClaimAttachmentHandler_Expecter) Create(c interface{}) *ClaimAttachmentHandler_Create_Call {
	return &ClaimAttachmentHandler_Create_Call{Call: _e.mock.On("Create", c)}
}

func (_c *ClaimAttachmentHandler_Create_Call) Run(run func(c *gin.Context)) *ClaimAttachmentHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *ClaimAttachmentHandler_Create_Call) Return() *ClaimAttachmentHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClaimAttachmentHandler_Create_Call) RunAndReturn(run func(*gin.Context)) *ClaimAttachmentHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// ClaimAttachmentHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ClaimAttachmentHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - c *gin.Context
func (_e *ClaimAttachmentHandler_Expecter) Delete(c interface{}) *ClaimAttachmentHandler_Delete_Call {
	return &ClaimAttachmentHandler_Delete_Call{Call: _e.mock.On("Delete", c)}
}

func (_c *ClaimAttachmentHandler_Delete_Call) Run(run func(c *gin.Context)) *ClaimAttachmentHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *ClaimAttachmentHandler_Delete_Call) Return() *ClaimAttachmentHandler_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClaimAttachmentHandler_Delete_Call) RunAndReturn(run func(*gin.Context)) *ClaimAttachmentHandler_Delete_Call {
	_c.Run(run)
	return _c
}

// GetByClaimID provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) GetByClaimID(c *gin.Context) {
	_m.Called(c)
}

// ClaimAttachmentHandler_GetByClaimID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClaimID'
type ClaimAttachmentHandler_GetByClaimID_Call struct {
	*mock.Call
}

// GetByClaimID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *ClaimAttachmentHandler_Expecter) GetByClaimID(c interface{}) *ClaimAttachmentHandler_GetByClaimID_Call {
	return &ClaimAttachmentHandler_GetByClaimID_Call{Call: _e.mock.On("GetByClaimID", c)}
}

func (_c *ClaimAttachmentHandler_GetByClaimID_Call) Run(run func(c *gin.Context)) *ClaimAttachmentHandler_GetByClaimID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *ClaimAttachmentHandler_GetByClaimID_Call) Return() *ClaimAttachmentHandler_GetByClaimID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClaimAttachmentHandler_GetByClaimID_Call) RunAndReturn(run func(*gin.Context)) *ClaimAttachmentHandler_GetByClaimID_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function with given fields: c
func (_m *ClaimAttachmentHandler) GetByID(c *gin.Context) {
	_m.Called(c)
}

// ClaimAttachmentHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ClaimAttachmentHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *ClaimAttachmentHandler_Expecter) GetByID(c interface{}) *ClaimAttachmentHandler_GetByID_Call {
	return &ClaimAttachmentHandler_GetByID_Call{Call: _e.mock.On("GetByID", c)}
}

func (_c *ClaimAttachmentHandler_GetByID_Call) Run(run func(c *gin.Context)) *ClaimAttachmentHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *ClaimAttachmentHandler_GetByID_Call) Return() *ClaimAttachmentHandler_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClaimAttachmentHandler_GetByID_Call) RunAndReturn(run func(*gin.Context)) *ClaimAttachmentHandler_GetByID_Call {
	_c.Run(run)
	return _c
}

// NewClaimAttachmentHandler creates a new instance of ClaimAttachmentHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimAttachmentHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimAttachmentHandler {
	mock := &ClaimAttachmentHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
