// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	oauth2 "golang.org/x/oauth2"

	providers "ev-warranty-go/internal/infrastructure/oauth/providers"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// ExchangeCode provides a mock function with given fields: ctx, code
func (_m *Provider) ExchangeCode(ctx context.Context, code string) (*oauth2.Token, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 *oauth2.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth2.Token, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth2.Token); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_ExchangeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCode'
type Provider_ExchangeCode_Call struct {
	*mock.Call
}

// ExchangeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *Provider_Expecter) ExchangeCode(ctx interface{}, code interface{}) *Provider_ExchangeCode_Call {
	return &Provider_ExchangeCode_Call{Call: _e.mock.On("ExchangeCode", ctx, code)}
}

func (_c *Provider_ExchangeCode_Call) Run(run func(ctx context.Context, code string)) *Provider_ExchangeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Provider_ExchangeCode_Call) Return(_a0 *oauth2.Token, _a1 error) *Provider_ExchangeCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_ExchangeCode_Call) RunAndReturn(run func(context.Context, string) (*oauth2.Token, error)) *Provider_ExchangeCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthURL provides a mock function with given fields: state
func (_m *Provider) GetAuthURL(state string) string {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Provider_GetAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthURL'
type Provider_GetAuthURL_Call struct {
	*mock.Call
}

// GetAuthURL is a helper method to define mock.On call
//   - state string
func (_e *Provider_Expecter) GetAuthURL(state interface{}) *Provider_GetAuthURL_Call {
	return &Provider_GetAuthURL_Call{Call: _e.mock.On("GetAuthURL", state)}
}

func (_c *Provider_GetAuthURL_Call) Run(run func(state string)) *Provider_GetAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Provider_GetAuthURL_Call) Return(_a0 string) *Provider_GetAuthURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_GetAuthURL_Call) RunAndReturn(run func(string) string) *Provider_GetAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function with given fields: ctx, token
func (_m *Provider) GetUserInfo(ctx context.Context, token *oauth2.Token) (*providers.UserInfo, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *providers.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) (*providers.UserInfo, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) *providers.UserInfo); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *oauth2.Token) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type Provider_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - token *oauth2.Token
func (_e *Provider_Expecter) GetUserInfo(ctx interface{}, token interface{}) *Provider_GetUserInfo_Call {
	return &Provider_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, token)}
}

func (_c *Provider_GetUserInfo_Call) Run(run func(ctx context.Context, token *oauth2.Token)) *Provider_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*oauth2.Token))
	})
	return _c
}

func (_c *Provider_GetUserInfo_Call) Return(_a0 *providers.UserInfo, _a1 error) *Provider_GetUserInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_GetUserInfo_Call) RunAndReturn(run func(context.Context, *oauth2.Token) (*providers.UserInfo, error)) *Provider_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Provider) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Provider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Provider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Provider_Expecter) Name() *Provider_Name_Call {
	return &Provider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Provider_Name_Call) Run(run func()) *Provider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Name_Call) Return(_a0 string) *Provider_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Name_Call) RunAndReturn(run func() string) *Provider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
