BEGIN;

DELETE FROM claim_attachments;
DELETE FROM claim_items;
DELETE FROM claim_histories;
DELETE FROM claims;
DELETE FROM users;
DELETE FROM offices;

TRUNCATE TABLE claim_histories CASCADE;
TRUNCATE TABLE claim_items CASCADE;
TRUNCATE TABLE claims CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE offices CASCADE;


COMMIT;